<?php

namespace Ko\MainBundle\Repository;

/**
 * CoordonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonateRepository extends \Doctrine\ORM\EntityRepository
{
}
