ko_main:
    resource: "@KoMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /registration/confirmed
    defaults: { _controller: KoMainBundle:Affichage:home }
    requirements:
        _method: GET

seen_notification:
    path: /seen_notification/{id}
    defaults: { _controller: AppBundle:Notification:seenNotification }

delete_notification:
    path: /delete_notification/{id}
    defaults: { _controller: AppBundle:Notification:seenNotification }