# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            Ko\UserBundle\Entity\User: sha512

    role_hierarchy:
            ROLE_ADMIN:       [ROLE_USER, ROLE_AUTEUR]
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_AUTEUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
         main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

            - { path: ^/team, role: ROLE_ADMIN }

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
