ko_project_homepage:
    path:     /home
    defaults: { _controller: KoProjectBundle:Project:index }

ko_project_accueil:
    path:     /
    defaults: { _controller: KoProjectBundle:Project:accueil }

ko_user_test:
    path:    /showw
    defaults: {_controller: KoUserBundle:Security:utilisateur}

bo_ilproject_post:
    resource: "routing/post/user.yml"
    prefix:   /post

