ko_project_homepage:
    path:     /home
    defaults: { _controller: KoProjectBundle:Project:index }

ko_project_accueil:
    path:     /
    defaults: { _controller: KoProjectBundle:Project:accueil }

ko_project_liste:
    path:     /liste
    defaults: { _controller: KoProjectBundle:ProjectAffichage:liste }
